version: '3'
services:
  db:
    build: ./docker/mysql
    restart: always
    volumes:
      - ./docker/mysql/persistence:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
    ports:
    - "3306"
  api:
    image: alpine:20191114
    restart: always
    entrypoint: /go-bin/sparschwein
    volumes:
      - ./docker/server:/go-bin
    ports:
    - "8000:8000"

